# Generated by Django 3.2.7 on 2021-09-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0006_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click Link above to read blog Post...', max_length=255),
        ),
    ]
