# Generated by Django 3.2.7 on 2021-11-09 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0013_auto_20211106_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title_tag',
            field=models.CharField(max_length=63),
        ),
    ]
